const PASSWORD_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789";
const ACTIVATION_SALT = "CDA-ATIVACAO-2026";
const CDA_KEY = "GerencialEscolar.CDA.Offline.v1";
let students = [], editingId = null, currentPhotoBase64 = "", photoZip = {}, logos = { central: "", esquerda: "", direita: "" };
const $ = (selector) => document.querySelector(selector);
const elements = { form: $("#student-form"), formTitle: $("#form-title"), studentCount: $("#student-count"), studentList: $("#students-list"), studentFilter: $("#student-filter"), bulkText: $("#bulk-import-text"), bulkFile: $("#bulk-file-input"), bulkSummary: $("#bulk-import-summary"), packageFile: $("#package-file-input"), photoInput: $("#student-photo-input"), photoStatus: $("#photo-review-status"), photoZipInput: $("#photos-zip-input"), photoZipStatus: $("#photos-zip-status"), toast: $("#toast") };

function normalize(value) { return String(value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, " ").trim().toUpperCase(); }
function key(student) { return `${normalize(student.nomeCompleto)}|${student.dataNascimento}`; }
function toast(message) { elements.toast.textContent = message; elements.toast.classList.add("visible"); setTimeout(() => elements.toast.classList.remove("visible"), 3500); }
function parseDate(value) { const text = String(value || "").trim(); const br = text.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/); if (br) return `${br[3]}-${br[2].padStart(2, "0")}-${br[1].padStart(2, "0")}`; return text; }
function splitLine(line, delimiter) { const output = []; let current = "", quoted = false; for (let i = 0; i < line.length; i += 1) { const char = line[i]; if (char === '"') quoted = !quoted; else if (char === delimiter && !quoted) { output.push(current.trim()); current = ""; } else current += char; } output.push(current.trim()); return output; }
function delimiter(line) { return line.includes("\t") ? "\t" : line.includes(";") ? ";" : ","; }
function parseRows(raw) { const lines = raw.replace(/^\uFEFF/, "").split(/\r?\n/).filter((line) => line.trim()); if (lines.length < 2) return []; const separator = delimiter(lines[0]); const letters = splitLine(lines[0], separator).map((value) => normalize(value)); const fields = letters.map((value) => /^[A-L]$/.test(value) ? value : null); if (!fields.some(Boolean)) throw new Error("A primeira linha deve indicar as letras A até L."); return lines.slice(1).map((line) => { const values = splitLine(line, separator); return Object.fromEntries(fields.map((field, index) => [field, values[index] || ""])); }); }
function fromRow(row, previous) { const academic = String(row.L || "").trim(); const student = { id: previous?.id || crypto.randomUUID(), registroAcademico: academic, nomeCompleto: String(row.A || "").trim(), nomeResponsavel: String(row.B || "").trim(), condicaoEspecifica: String(row.C || "").trim() || undefined, retiradaAutorizada: String(row.D || "").trim() || undefined, telefoneResponsavel: String(row.E || "").trim() || undefined, dataNascimento: parseDate(row.F), anoSerie: String(row.G || "").trim(), sala: String(row.H || "").trim(), turno: String(row.I || "").trim(), professora: String(row.J || "").trim(), auxiliar: String(row.K || "").trim(), fotoBase64: previous?.fotoBase64 || photoZip[`${academic}.jpg`] || photoZip[`${academic}.jpeg`] || undefined, atualizadoEm: new Date().toISOString() }; return [student.nomeCompleto, student.nomeResponsavel, student.dataNascimento, student.anoSerie, student.sala, student.turno, student.professora, student.auxiliar, academic].every(Boolean) ? student : null; }
function mergeRows(rows) { const index = new Map(students.map((student, i) => [key(student), i])); const merged = [...students]; let added = 0, updated = 0, ignored = 0; rows.forEach((row) => { const existingIndex = index.get(`${normalize(row.A)}|${parseDate(row.F)}`); const student = fromRow(row, existingIndex === undefined ? undefined : merged[existingIndex]); if (!student) { ignored += 1; return; } if (existingIndex === undefined) { index.set(key(student), merged.length); merged.push(student); added += 1; } else { merged[existingIndex] = student; updated += 1; } }); students = merged; renderStudents(); const summary = `${added} adicionado(s), ${updated} atualizado(s), ${ignored} ignorado(s).`; elements.bulkSummary.textContent = summary; toast(summary); }
function randomPassword() { let result = ""; while (new Set(result).size !== 4 || !result) { const available = PASSWORD_ALPHABET.split(""); result = Array.from({ length: 4 }, () => available.splice(Math.floor(Math.random() * available.length), 1)[0]).join(""); } return result; }
function passwordFromHash(hex) { const available = PASSWORD_ALPHABET.split(""), chosen = []; let i = 0; while (chosen.length < 4) { chosen.push(available.splice(Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16) % available.length, 1)[0]); i += 1; } return chosen.join(""); }
function cpfValid(value) { const cpf = value.replace(/\D/g, ""); if (!/^\d{11}$/.test(cpf) || /^(\d)\1{10}$/.test(cpf)) return false; const digit = (length) => { const sum = cpf.slice(0, length).split("").reduce((total, character, index) => total + Number(character) * (length + 1 - index), 0); const answer = (sum * 10) % 11; return answer === 10 ? 0 : answer; }; return digit(9) === Number(cpf[9]) && digit(10) === Number(cpf[10]); }
function activationPassword() { const cpf = $("#activation-cpf-input").value.replace(/\D/g, ""); const code = $("#activation-code-input").value.trim().toUpperCase(); const months = $("#activation-months").value; if (!cpfValid(cpf) || !/^[A-Z1-9]{8}$/.test(code)) { alert("Informe um CPF válido e o código de 8 caracteres mostrado no Android."); return; } $("#activation-password-output").textContent = passwordFromHash(CryptoJS.SHA256(`${ACTIVATION_SALT}|${cpf}|${code}|${months}`).toString()); }
function renderStudents() { const search = normalize(elements.studentFilter.value); const filtered = students.filter((student) => !search || normalize(`${student.nomeCompleto} ${student.registroAcademico}`).includes(search)); elements.studentCount.textContent = String(students.length); elements.studentList.innerHTML = ""; if (!filtered.length) { elements.studentList.innerHTML = `<p class="empty-list">${students.length ? "Nenhum aluno encontrado." : "Nenhum aluno cadastrado."}</p>`; return; } const template = $("#student-item-template"); filtered.sort((a, b) => a.nomeCompleto.localeCompare(b.nomeCompleto, "pt-BR")).forEach((student) => { const node = template.content.cloneNode(true); node.querySelector(".student-avatar").textContent = student.nomeCompleto.charAt(0); node.querySelector(".student-name").textContent = student.nomeCompleto; node.querySelector(".student-meta").textContent = `${student.registroAcademico} · ${student.anoSerie} · ${student.sala}`; node.querySelector(".edit").onclick = () => beginEdit(student.id); node.querySelector(".delete").onclick = () => removeStudent(student.id); elements.studentList.append(node); }); }
function field(id) { return $(`#${id}`); }
function resetForm() { editingId = null; currentPhotoBase64 = ""; elements.form.reset(); elements.formTitle.textContent = "Novo aluno"; elements.photoStatus.textContent = "Escolha um aluno e inclua ou substitua a foto individual."; }
function beginEdit(id) { const student = students.find((item) => item.id === id); if (!student) return; editingId = id; currentPhotoBase64 = student.fotoBase64 || ""; Object.assign(field("nome-completo"), { value: student.nomeCompleto }); Object.assign(field("nome-responsavel"), { value: student.nomeResponsavel }); Object.assign(field("telefone-responsavel"), { value: student.telefoneResponsavel || "" }); Object.assign(field("data-nascimento"), { value: student.dataNascimento }); Object.assign(field("ano-serie"), { value: student.anoSerie }); Object.assign(field("sala"), { value: student.sala }); Object.assign(field("turno"), { value: student.turno }); Object.assign(field("professora"), { value: student.professora || "" }); Object.assign(field("auxiliar"), { value: student.auxiliar || "" }); Object.assign(field("registro-academico"), { value: student.registroAcademico || "" }); Object.assign(field("condicao-especifica"), { value: student.condicaoEspecifica || "" }); Object.assign(field("retirada-autorizada"), { value: student.retiradaAutorizada || "" }); elements.formTitle.textContent = "Revisar aluno e foto"; elements.photoStatus.textContent = currentPhotoBase64 ? "Foto já presente; escolha outro arquivo para substituir." : "Sem foto: escolha um arquivo para associar a este aluno."; document.querySelector(".form-panel").scrollIntoView({ behavior: "smooth" }); }
function removeStudent(id) { const student = students.find((item) => item.id === id); if (student && confirm(`Excluir ${student.nomeCompleto}?`)) { students = students.filter((item) => item.id !== id); renderStudents(); resetForm(); } }
function dataUrl(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
function onSave(event) { event.preventDefault(); const student = { id: editingId || crypto.randomUUID(), nomeCompleto: field("nome-completo").value.trim(), nomeResponsavel: field("nome-responsavel").value.trim(), telefoneResponsavel: field("telefone-responsavel").value.trim() || undefined, dataNascimento: field("data-nascimento").value, anoSerie: field("ano-serie").value.trim(), sala: field("sala").value.trim(), turno: field("turno").value.trim(), professora: field("professora").value.trim(), auxiliar: field("auxiliar").value.trim(), registroAcademico: field("registro-academico").value.trim(), condicaoEspecifica: field("condicao-especifica").value.trim() || undefined, retiradaAutorizada: field("retirada-autorizada").value.trim() || undefined, fotoBase64: currentPhotoBase64 || undefined, atualizadoEm: new Date().toISOString() }; if (!Object.values({ ...student, fotoBase64: "ok", condicaoEspecifica: "ok", retiradaAutorizada: "ok", telefoneResponsavel: "ok", atualizadoEm: "ok" }).every(Boolean)) return; students = students.filter((item) => item.id !== student.id && key(item) !== key(student)); students.push(student); renderStudents(); resetForm(); toast("Aluno salvo."); }
function bytesToDataUrl(bytes, name) { let binary = ""; for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return `data:image/${name.toLowerCase().endsWith(".png") ? "png" : "jpeg"};base64,${btoa(binary)}`; }
async function loadPhotoZip(file) { const files = fflate.unzipSync(new Uint8Array(await file.arrayBuffer())); photoZip = Object.fromEntries(Object.entries(files).filter(([name]) => /\.jpe?g$/i.test(name)).map(([name, bytes]) => [name.split("/").pop(), bytesToDataUrl(bytes, name)])); elements.photoZipStatus.textContent = `${Object.keys(photoZip).length} foto(s) disponível(is) no ZIP.`; toast("ZIP de fotos carregado."); }
async function setLogo(kind, file) { if (!file) return; const image = await dataUrl(file); if (kind === "central") logos = { central: image, esquerda: "", direita: "" }; if (kind === "esquerda") logos = { ...logos, central: "", esquerda: image }; if (kind === "direita") logos = { ...logos, central: "", direita: image }; toast("Logo atualizado segundo as regras de posição."); }
function wordArrayToU8(wordArray) { const { words, sigBytes } = wordArray; const bytes = new Uint8Array(sigBytes); for (let i = 0; i < sigBytes; i += 1) bytes[i] = (words[i >>> 2] >>> (24 - (i % 4) * 8)) & 0xff; return bytes; }
function packageData() { const created = new Date().toISOString(); const photoFiles = {}; const dataStudents = students.map((student) => { const clone = { ...student }; if (student.fotoBase64) { const filename = `${student.registroAcademico}.jpg`; photoFiles[`fotos/${filename}`] = fflate.strToU8(student.fotoBase64); clone.fotoArquivo = filename; delete clone.fotoBase64; } return clone; }); const files = { "dados.json": fflate.strToU8(JSON.stringify({ formato: "consulta-alunos-import", versao: 2, exportadoEm: created, criadoEm: created, origem: "Gerencial Escolar — Administrativo", logos, alunos: dataStudents })) }; Object.entries(photoFiles).forEach(([name, value]) => { files[name] = value; }); Object.entries(logos).forEach(([kind, value]) => { if (value) files[`logos/${kind}.jpeg`] = fflate.strToU8(value); }); return { created, zip: fflate.zipSync(files, { level: 6 }) }; }
async function exportCda() { const { created, zip } = packageData(); const cipher = CryptoJS.AES.encrypt(CryptoJS.lib.WordArray.create(zip), CDA_KEY).toString(); const payload = JSON.stringify({ formato: "gerencial-escolar-cda", versao: 1, criadoEm: created, payload: cipher }); const filename = `atualizacao_${created.slice(0, 10)}.cda`; if (window.adminApi?.savePackage) { const result = await window.adminApi.savePackage({ content: payload, fileName: filename }); if (result.saved) toast(`CDA salvo em ${result.filePath}`); return; } const blob = new Blob([payload], { type: "application/octet-stream" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); toast("Arquivo CDA salvo pelo navegador."); }
async function openPackage(file) { const raw = await file.text(); if (/\.cda$/i.test(file.name)) { const envelope = JSON.parse(raw); const zip = wordArrayToU8(CryptoJS.AES.decrypt(envelope.payload, CDA_KEY)); const unpacked = fflate.unzipSync(zip); const data = JSON.parse(fflate.strFromU8(unpacked["dados.json"])); students = data.alunos || []; logos = data.logos || logos; renderStudents(); toast(`${students.length} aluno(s) carregado(s) do CDA.`); return; } const data = JSON.parse(raw); students = data.alunos || []; logos = data.logos || logos; renderStudents(); toast(`${students.length} aluno(s) carregado(s).`); }
function manual() { $("#manual-content").innerHTML = `<h3>1. Criar a tabela</h3><p>Use A para nome, B responsável, C aviso amarelo, D recado de saída, E telefone do responsável, F nascimento, G ano/série, H sala, I turno, J professora, K auxiliar e L registro acadêmico único. A primeira linha tem A–L; os alunos começam na segunda.</p><h3>2. Importar</h3><p>Cole diretamente da planilha ou use CSV, TSV, TXT, XLS ou XLSX. O programa lê as letras A–L independentemente da posição das colunas.</p><h3>3. Fotos e logos</h3><p>Fotos ficam no ZIP com o mesmo nome de L, por exemplo NA00001.jpg. institucional.jpeg é central; institucional1.jpeg ocupa a esquerda; institucional2.jpeg ocupa a direita. O central substitui os menores; os menores preservam o oposto.</p><h3>4. Pesquisa e conferência</h3><p>O Android entende nome aproximado, mãe/mae/resp, sala, prof, aux, turno, ano, série, nota, aniversário, telefone e registro. A conferência mantém filtros e cores até os botões de lixeira ou seta circular.</p><h3>5. Senhas e ativação</h3><p>Após três falhas em aberturas distintas, o usuário informa CPF e recebe código de 8 caracteres. Informe CPF, código e validade desejada aqui para gerar a senha nova.</p><h3>6. Atualização CDA</h3><p>Gerar atualização cria um CDA comprimido e cifrado com dados, fotos, logos e data do computador. É o arquivo levado ao Android.</p>`; $("#help-modal").hidden = false; }
elements.form.addEventListener("submit", onSave); elements.studentFilter.addEventListener("input", renderStudents); $("#clear-form-button").onclick = resetForm; $("#cancel-edit-button").onclick = resetForm; $("#remove-photo-button").onclick = () => { currentPhotoBase64 = ""; elements.photoStatus.textContent = "Foto removida."; }; elements.photoInput.addEventListener("change", async (event) => { const file = event.target.files[0]; if (file) { currentPhotoBase64 = await dataUrl(file); elements.photoStatus.textContent = `Foto pronta: ${file.name}`; } }); $("#bulk-import-text-button").onclick = () => { try { mergeRows(parseRows(elements.bulkText.value)); } catch (error) { alert(error.message); } }; $("#bulk-import-file-button").onclick = () => elements.bulkFile.click(); elements.bulkFile.addEventListener("change", async (event) => { const file = event.target.files[0]; if (!file) return; try { if (/\.xlsx?$/i.test(file.name)) { const workbook = XLSX.read(await file.arrayBuffer(), { type: "array" }); const worksheet = workbook.Sheets[workbook.SheetNames[0]]; const table = XLSX.utils.sheet_to_csv(worksheet); mergeRows(parseRows(table)); } else mergeRows(parseRows(await file.text())); } catch (error) { alert(error.message); } }); elements.photoZipInput.addEventListener("change", (event) => { const file = event.target.files[0]; if (file) void loadPhotoZip(file); }); $("#logo-central-input").addEventListener("change", (event) => void setLogo("central", event.target.files[0])); $("#logo-left-input").addEventListener("change", (event) => void setLogo("esquerda", event.target.files[0])); $("#logo-right-input").addEventListener("change", (event) => void setLogo("direita", event.target.files[0])); $("#activation-password-button").onclick = activationPassword; $("#random-password-button").onclick = () => { $("#random-password-output").textContent = randomPassword(); }; $("#export-button").onclick = () => void exportCda(); $("#import-button").onclick = () => elements.packageFile.click(); elements.packageFile.addEventListener("change", (event) => { const file = event.target.files[0]; if (file) void openPackage(file); }); $("#manual-button").onclick = manual; $("#close-manual-button").onclick = () => { $("#help-modal").hidden = true; }; renderStudents();
