import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router, type Href } from "expo-router";

import { AppFooter } from "@/components/app-footer";
import { ScreenContainer } from "@/components/screen-container";
import { getMetadata, getPassword, saveMetadata, savePassword } from "@/lib/app-storage";
import { expiryForMonths, generateChoiceBoard, generateRecoveryChoiceBoard, getRecoveryActivationCode, isLicenseValid, passwordForRecovery, temporaryPasswordAvailable, validateCpf } from "@/lib/security";
import type { AppMetadata } from "@/shared/student";

type Candidate = { months: number; password: string };

export default function AccessScreen() {
  const [loading, setLoading] = useState(true); const [metadata, setMetadata] = useState<AppMetadata | null>(null); const [password, setPassword] = useState(""); const [position, setPosition] = useState(0); const [choices, setChoices] = useState<string[]>([]); const [correctIndex, setCorrectIndex] = useState(-1); const [blocked, setBlocked] = useState(false); const [activation, setActivation] = useState(false); const [cpf, setCpf] = useState(""); const [activationCode, setActivationCode] = useState(""); const [candidates, setCandidates] = useState<Candidate[]>([]);
  const recoveryMode = activation && candidates.length > 0;

  const setupPassword = useCallback(async (target: string, nextPosition: number) => { const board = await generateChoiceBoard(target, nextPosition); setChoices(board.choices); setCorrectIndex(board.correctIndex); }, []);
  const setupRecovery = useCallback(async (items: Candidate[], nextPosition: number) => { setChoices(await generateRecoveryChoiceBoard(items.map((item) => item.password), nextPosition)); setCorrectIndex(-1); }, []);
  useEffect(() => { async function prepare() { const current = await getMetadata(); const stored = await getPassword(); const needsActivation = current.exigeAtivacao || (!isLicenseValid(current.licencaExpiraEm) && !temporaryPasswordAvailable(current.instaladoEm)); setMetadata(current); setActivation(needsActivation); if (!needsActivation) { setPassword(stored); await setupPassword(stored, 0); } setLoading(false); } void prepare(); }, [setupPassword]);

  const blockFailure = async () => { if (!metadata) return; const failures = metadata.falhasDeSenha + 1; const next = { ...metadata, falhasDeSenha: failures, exigeAtivacao: failures >= 3 }; await saveMetadata(next); setMetadata(next); setBlocked(true); setChoices(["ABC", "DEF", "GHI", "JKL"]); };
  const chooseNormal = async (index: number) => { if (blocked || !metadata) return; if (index !== correctIndex) { await blockFailure(); return; } const nextPosition = position + 1; if (nextPosition === password.length) { const next = { ...metadata, falhasDeSenha: 0 }; await saveMetadata(next); router.replace("/menu" as Href); return; } setPosition(nextPosition); await setupPassword(password, nextPosition); };
  const beginActivation = async () => { if (!metadata || !validateCpf(cpf)) return; const code = await getRecoveryActivationCode(cpf, metadata.identificadorInstalacao); setActivationCode(code); const values = await Promise.all([2, 4, 6, 8, 10, 12].map(async (months) => ({ months, password: await passwordForRecovery(cpf, code, months) }))); setCandidates(values); setPosition(0); await setupRecovery(values, 0); };
  const chooseRecovery = async (index: number) => { if (blocked || !metadata) return; const option = choices[index]; const narrowed = candidates.filter((candidate) => option.includes(candidate.password[position])); if (!narrowed.length) { setBlocked(true); return; } const nextPosition = position + 1; if (nextPosition === 4) { const selected = narrowed[0]; const next = { ...metadata, falhasDeSenha: 0, exigeAtivacao: false, licencaExpiraEm: expiryForMonths(selected.months) }; await savePassword(selected.password); await saveMetadata(next); router.replace("/menu" as Href); return; } setCandidates(narrowed); setPosition(nextPosition); await setupRecovery(narrowed, nextPosition); };
  const cpfValid = useMemo(() => validateCpf(cpf), [cpf]);
  if (loading) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="items-center justify-center"><ActivityIndicator color="#0E7490" size="large" /></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F5F7FA]"><View style={styles.page}><View style={styles.content}><View style={styles.brand}><Text style={styles.brandText}>GE</Text></View><Text style={styles.title}>Gerencial Escolar</Text><Text style={styles.subtitle}>Acesso restrito à equipe escolar</Text>{activation && !recoveryMode ? <View style={styles.card}><Text style={styles.activationTitle}>ATIVAÇÃO NECESSÁRIA</Text><Text style={styles.activationText}>Informe o CPF de 11 dígitos para mostrar o código de ativação do aparelho.</Text><TextInput value={cpf} onChangeText={(value) => setCpf(value.replace(/\D/g, "").slice(0, 11))} keyboardType="numeric" placeholder="CPF" placeholderTextColor="#8795A2" style={styles.cpfInput} /><Text style={styles.cpfHint}>{cpf.length === 11 && !cpfValid ? "CPF inválido" : ""}</Text><Pressable disabled={!cpfValid} onPress={() => void beginActivation()} style={({ pressed }) => [styles.primary, !cpfValid && styles.disabled, pressed && styles.pressed]}><Text style={styles.primaryText}>MOSTRAR CÓDIGO</Text></Pressable></View> : <View style={styles.card}>{recoveryMode ? <View style={styles.codeBox}><Text style={styles.codeLabel}>CÓDIGO DE ATIVAÇÃO</Text><Text selectable style={styles.code}>{activationCode}</Text><Text style={styles.codeHelp}>Informe CPF e código na versão administrativa para receber a nova senha.</Text></View> : null}<Text style={styles.instruction}>Escolha a opção que contém o próximo caractere da senha.</Text><View style={styles.grid}>{choices.map((choice, index) => <Pressable key={`${choice}-${index}`} onPress={() => void (recoveryMode ? chooseRecovery(index) : chooseNormal(index))} style={({ pressed }) => [styles.choice, pressed && !blocked && styles.pressed]}><Text style={styles.choiceText}>{choice}</Text></Pressable>)}</View></View>}</View><AppFooter /></View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, padding: 22 }, content: { flex: 1, maxWidth: 460, width: "100%", alignSelf: "center", justifyContent: "center", gap: 11 }, brand: { width: 58, height: 58, borderRadius: 18, backgroundColor: "#0E7490", alignItems: "center", justifyContent: "center", marginBottom: 5 }, brandText: { color: "#FFFFFF", fontSize: 20, fontWeight: "900" }, title: { color: "#163047", fontSize: 29, fontWeight: "900" }, subtitle: { color: "#5C7181", fontSize: 15, marginBottom: 12 }, card: { backgroundColor: "#FFFFFF", borderRadius: 20, borderWidth: 1, borderColor: "#DDE5ED", padding: 19, gap: 16 }, instruction: { color: "#43596A", fontSize: 15, lineHeight: 21, textAlign: "center" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, choice: { width: "48%", minHeight: 61, borderRadius: 12, backgroundColor: "#12365A", justifyContent: "center", alignItems: "center" }, choiceText: { color: "#FFFFFF", fontSize: 20, letterSpacing: 5, fontWeight: "900", marginLeft: 5 }, activationTitle: { color: "#0D5E77", fontSize: 12, letterSpacing: 1, fontWeight: "900" }, activationText: { color: "#4F6475", fontSize: 14, lineHeight: 20 }, cpfInput: { minHeight: 48, borderWidth: 1, borderColor: "#CBD9E4", borderRadius: 10, paddingHorizontal: 12, color: "#173449", fontSize: 17, letterSpacing: 1 }, cpfHint: { color: "#B03939", fontSize: 12, minHeight: 16 }, primary: { minHeight: 48, borderRadius: 11, backgroundColor: "#0E7490", alignItems: "center", justifyContent: "center" }, primaryText: { color: "#FFFFFF", fontWeight: "900", fontSize: 13 }, disabled: { opacity: 0.45 }, codeBox: { padding: 13, borderRadius: 12, backgroundColor: "#E6F3F7", gap: 5 }, codeLabel: { color: "#0D5E77", fontSize: 11, fontWeight: "900", letterSpacing: 1 }, code: { color: "#0D5E77", fontSize: 20, fontWeight: "900", letterSpacing: 2 }, codeHelp: { color: "#496779", fontSize: 12, lineHeight: 17 }, pressed: { opacity: 0.77, transform: [{ scale: 0.98 }] },
});
