import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import { useState } from "react";
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";

import { AppFooter } from "@/components/app-footer";
import { ActionButton } from "@/components/action-button";
import { ScreenContainer } from "@/components/screen-container";
import { useAppData } from "@/lib/app-provider";
import { savePassword } from "@/lib/app-storage";
import { parseUpdatePackage } from "@/lib/cda-package";
import { countDuplicates } from "@/lib/importer";
import { generatePassword } from "@/lib/security";

export default function SettingsScreen() {
  const { students, importPackage, resetApp } = useAppData();
  const [busy, setBusy] = useState(false); const [confirmation, setConfirmation] = useState(""); const [resetVisible, setResetVisible] = useState(false);
  const processPackage = async (raw: string) => { const data = parseUpdatePackage(raw); const duplicates = countDuplicates(students, data.alunos); const proceed = async () => { const summary = await importPackage(data); Alert.alert("Importação concluída", `${summary.adicionados} aluno(s) adicionados, ${summary.atualizados} atualizados. Total: ${summary.total}.`); }; if (duplicates) Alert.alert("Duplicidades encontradas", `${duplicates} aluno(s) têm o mesmo nome e data de nascimento e serão substituídos.`, [{ text: "Cancelar", style: "cancel" }, { text: "Confirmar", onPress: () => void proceed() }]); else await proceed(); };
  const importData = async () => { try { const result = await DocumentPicker.getDocumentAsync({ type: ["application/json", "text/json", "text/plain", "*/*"], copyToCacheDirectory: true }); if (result.canceled) return; setBusy(true); const raw = await FileSystem.readAsStringAsync(result.assets[0].uri, { encoding: FileSystem.EncodingType.UTF8 }); await processPackage(raw); } catch (error) { Alert.alert("Importação não concluída", error instanceof Error ? error.message : "Não foi possível ler o arquivo."); } finally { setBusy(false); } };
  const newPassword = async () => { const password = await generatePassword(); await savePassword(password); Alert.alert("Nova senha", `Aprenda ou anote esta senha antes de fechar:\n\n${password}\n\nVocê pode gerar outra quantas vezes precisar; a última será a senha de entrada.`); };
  const doReset = async () => { setBusy(true); await resetApp(); setBusy(false); setResetVisible(false); router.replace("/"); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F5F7FA]"><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" color="#12365A" size={23} /></Pressable><Text style={styles.title}>Dados e acesso</Text><View style={styles.back} /></View><View style={styles.card}><Text style={styles.section}>IMPORTAR BANCO</Text><Text style={styles.copy}>Abra a pesquisa de arquivos do telefone — inclusive Google Drive — e selecione o banco JSON ou atualização compatível. Duplicidades serão confirmadas antes da substituição.</Text><ActionButton label={busy ? "IMPORTANDO…" : "IMPORTAR"} onPress={() => void importData()} disabled={busy} /></View><View style={styles.card}><Text style={styles.section}>GERAR SENHA</Text><Text style={styles.copy}>Cria uma senha local nova de 4 caracteres. A última senha gerada será exigida quando o aplicativo for aberto novamente.</Text><ActionButton label="GERAR NOVA SENHA" onPress={() => void newPassword()} variant="secondary" disabled={busy} /></View><View style={styles.danger}><Text style={styles.dangerTitle}>REINICIAR DADOS LOCAIS</Text><Text style={styles.copy}>Apaga os alunos deste aparelho, a conferência e as configurações de acesso. Para continuar será necessário importar uma nova base.</Text><ActionButton label="REINICIAR" onPress={() => { setConfirmation(""); setResetVisible(true); }} variant="danger" disabled={busy} /></View><AppFooter /></ScrollView><Modal visible={resetVisible} transparent animationType="fade" onRequestClose={() => setResetVisible(false)}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.modalTitle}>Confirmar exclusão</Text><Text style={styles.copy}>Digite exatamente CONFIRMO para apagar os dados locais.</Text><TextInput value={confirmation} onChangeText={setConfirmation} autoCapitalize="characters" autoCorrect={false} maxLength={8} placeholder="CONFIRMO" style={styles.input} /><View style={styles.modalActions}><ActionButton label="CANCELAR" onPress={() => setResetVisible(false)} variant="secondary" style={styles.action} /><ActionButton label="APAGAR" onPress={() => void doReset()} disabled={confirmation !== "CONFIRMO"} variant="danger" style={styles.action} /></View></View></View></Modal></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 28, gap: 15 }, top: { minHeight: 42, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, back: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#E5EEF6", alignItems: "center", justifyContent: "center" }, title: { color: "#173449", fontSize: 18, fontWeight: "900" }, card: { backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: "#DCE7EF", padding: 17, gap: 12 }, section: { color: "#0D5E77", fontSize: 12, fontWeight: "900", letterSpacing: 1 }, copy: { color: "#4D6273", fontSize: 14, lineHeight: 20 }, danger: { backgroundColor: "#FFF4F4", borderRadius: 16, borderWidth: 1, borderColor: "#F1CFCF", padding: 17, gap: 12 }, dangerTitle: { color: "#983636", fontSize: 12, fontWeight: "900", letterSpacing: 1 }, overlay: { flex: 1, backgroundColor: "rgba(12,31,45,0.48)", padding: 22, justifyContent: "center" }, modal: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 21, gap: 14 }, modalTitle: { color: "#8B2C2C", fontSize: 20, fontWeight: "900" }, input: { height: 48, borderColor: "#CFDAE4", borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, color: "#173449", fontSize: 16, fontWeight: "900", letterSpacing: 1 }, modalActions: { flexDirection: "row", gap: 10 }, action: { flex: 1 },
});
